apiVersion: v1
kind: Pod
metadata:
  name: spark-deployment
  namespace: default
spec:
  containers:
  - name: spark-xgboost-sgx-example
    image: xgboost-spark-sgx
    imagePullPolicy: Never
    volumeMounts:
    - name: sgx-enclave
      mountPath: /dev/sgx/enclave
    - name: sgx-provision
      mountPath: /dev/sgx/provision
    - name: data-exchange
      mountPath: /opt/occlum_spark/data
    securityContext:
      privileged: true
  volumes:
  - name: sgx-enclave
    hostPath:
      path: /dev/sgx_enclave
  - name: sgx-provision
    hostPath:
      path: /dev/sgx_provision
  - name: data-exchange
    hostPath:
      path: /tmp