apiVersion: v1
kind: Pod
metadata:
  name: spark-deployment
  namespace: default
spec:
  containers:
    - name: spark-example
      image: $IMAGE
      imagePullPolicy: Never
      volumeMounts:
        - name: sgx-enclave
          mountPath: /dev/sgx/enclave
        - name: sgx-provision
          mountPath: /dev/sgx/provision
        - name: aesm
          mountPath: /var/run/aesmd/aesm.socket
        - name: data-exchange
          mountPath: /opt/occlum_spark/data
      securityContext:
        privileged: true
      env:
        - name: SGX_MEM_SIZE
          value: "20GB"
        - name: SGX_THREAD
          value: "512"
        - name: SGX_HEAP
          value: "512MB"
        - name: SGX_KERNEL_HEAP
          value: "1GB"
  volumes:
    - name: sgx-enclave
      hostPath:
        path: /dev/sgx_enclave
    - name: sgx-provision
      hostPath:
        path: /dev/sgx_provision
    - name: aesm
      hostPath:
        path: /var/run/aesmd/aesm.socket
    - name: data-exchange
      hostPath:
        path: /tmp