apiVersion: v1
kind: Pod
metadata:
  name: spark-deployment
  namespace: default
spec:
  containers:
    - name: spark-example
      image: xgboost-spark-sgx:1.0.0
      imagePullPolicy: Never
      volumeMounts:
        - name: sgx-enclave
          mountPath: /dev/sgx/_enclave
        - name: sgx-provision
          mountPath: /dev/sgx/_provision
        - name: aesm
          mountPath: /var/run/aesmd/aesm.socket
        - name: data-exchange
          mountPath: /opt/occlum_spark/data
      securityContext:
        privileged: true
      env:
        - name: SGX_MEM_SIZE
          value: "40GB"
        - name: SGX_THREAD
          value: "1024"
        - name: SGX_HEAP
          value: "20GB"
        - name: SGX_KERNEL_HEAP
          value: "1GB"
        - name: META_SPACE
          value: 1024m
  volumes:
    - name: sgx-enclave
      hostPath:
        path: /dev/sgx_enclave
    - name: sgx-provision
      hostPath:
        path: /dev/sgx_provision
    - name: aesm
      hostPath:
        path: /var/run/aesmd/aesm.socket
    - name: data-exchange
      nfs:
        server:
        path: /disk1/nfsdata